# Generated by Django 5.2.15 on 2026-06-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='history/')),
                ('is_lemon_leaf', models.BooleanField(default=False)),
                ('disease', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
